package com.example.simple.jira.model.domain;

/**
 * Immutable representation of a single task within a project
 *
 * @author spacedesk2
 * @version 1.0
 */
public final class Task {

    /** Identifier of the task generated by the repository. */
    private final int taskId;
    /** Human readable title summarizing the work item. */
    private final String title;
    /** Detailed description of the work item. */
    private final String description;
    /** Current status of the task. */
    private final TaskStatus status;
    /** Identifier of the project to which the task belongs. */
    private final int projectId;
    /** Priority level of the task. */
    private final TaskPriority priority;
    /**
     * Creates a new immutable task instance
     *
     * @param taskId identifier generated by the repository
     * @param title short summary of the task
     * @param description detailed description of the work item
     * @param status current workflow status
     * @param priority priority level of the task
     * @param projectId owning project identifier
     */
    public Task(final int taskId, final String title, final String description, final TaskStatus status, final TaskPriority priority, final int projectId) {
        this.taskId = taskId;
        this.title = title;
        this.description = description;
        this.status = status;
        this.projectId = projectId;
        this.priority = priority;
    }

    /**
     * Returns the task identifier
     *
     * @return immutable task identifier
     */
    public int getTaskId() {
        return taskId;
    }

    /**
     * Returns the task title
     *
     * @return immutable title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the task description
     *
     * @return immutable description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns the current status of the task
     *
     * @return workflow status
     */
    public TaskStatus getStatus() {
        return status;
    }

    /**
     * Returns the priority level of the task
     *
     * @return immutable priority level
     */
    public TaskPriority getPriority() {
        return priority;
    }

    /**
     * Returns the identifier of the owning project
     *
     * @return immutable project identifier
     */
    public int getProjectId() {
        return projectId;
    }

    /**
     * Creates a copy of the task with a new status
     *
     * @param newStatus updated workflow status
     * @return task copy reflecting the new status
     */
    public Task withStatus(final TaskStatus newStatus) {
        return new Task(taskId, title, description, newStatus, priority, projectId);
    }

    /**
     * Creates a copy of the task with updated priority
     *
     * @param newPriority new priority level
     * @return task copy reflecting the new priority
     */
    public Task withPriority(final TaskPriority newPriority) {
        return new Task(taskId, title, description, status, newPriority, projectId);
    }

    /**
     * Creates a copy of the task with updated textual description
     *
     * @param newTitle new title value
     * @param newDescription new description value
     * @return task copy with updated textual fields
     */
    public Task withDetails(final String newTitle, final String newDescription) {
        return new Task(taskId, newTitle, newDescription, status, priority, projectId);
    }
}




